##
# production.json
# production config values
#
# secrets and credentials should not be commited to git.  set these values to undefined to require
# their definitions from ENV variables.
#

##
# configuration required for the express app
#
app:
  # the port the app should listen to (integer)
  port: undefined

##
# configuration required for mongodb
#
mongoDB:
  # url of mongodb database (string)
  location: undefined

##
# configuration required for the logger module
#
logger:
  # mongodb transport
  mongoDB:
    # if mongoDB transport is enabled (bool)
    enabled: true
  # daily-rotate-file transport
  dailyRotateFile:
    # if winston-daily-rotate-file transport is enabled (bool)
    enabled: false
    # maximum file size before creating a new file in bytes (integer)
    maxFileSize: null
    # maximum number of files before deleting the oldest (integer)
    maxFiles: null
    # directory location to save logs (string)
    logDirectory: null

##
# configuration required for session management
#
auth:
  # Secret used to encrypt session cookies (string)
  secret: undefined
  # how long the token will be valid in sed (integer)
  expiresIn: 86400

##
# configuration required for the email module
#
mailer:
  # if mailer is enabled (bool)
  enabled: true
  # email account to send emails from (string)
  email: undefined
  # email account password (string)
  password: undefined
